[package]
name = "pwnenv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
log = "0.4.28"
rusqlite = "0.37.0"
simple_logger = "5.1.0"
tabled = "0.20.0"
uuid = { version = "1.18.1", features = ["v4"] }
